# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_first_notebook.ipynb.

# %% auto 0
__all__ = ['foo', 'bar']

# %% ../nbs/00_first_notebook.ipynb 7
def foo():
    pass

# %% ../nbs/00_first_notebook.ipynb 8
def bar():
    pass
